### PR TITLE
Update for master branch iced

### PR DESCRIPTION
**Pull request by robbert-vdh**
Lots of things going on here that should not yet be merged into `iced_baseview` (they're all development versions), but I thought it might be a good idea to have this PR up anyways in case someone also needs this. With these changes the wgpu backend gets updated from 0.7.1 to 0.12 which should fix a couple of crashes and other stability issues. The glow backend also get patched to use baseview's new OpenGL context management. I'll also work on adding better keyboard modifier handling (that's already in here) and clipboard support.

### CODE REVIEW

**Comment by robbert-vdh** [comment]
I've also added clipboard support.

**Comment by greatest-ape** [comment]
FYI there is an iced_git branch that you might want to merge against :-) https://github.com/BillyDM/iced_baseview/tree/iced_git

**Comment by BillyDM** [comment]
> FYI there is an iced_git branch that you might want to merge against :-) https://github.com/BillyDM/iced_baseview/tree/iced_git

Definitely. Put the pull request there please.

**Comment by robbert-vdh** [comment]
Re: the changes on that branch, can I revert the feature names back to the original iced features? And do we need the log crate? That's what the debug overlay is for. I've never seen canonical Rust crates prefix their features with `with-`, so it seems strange to do that here especially if it they're supposed to be one to one equivalent feature flag forwards for those on the regular `iced` crate. And why is the anti aliasing option glow-specific, wouldn't you also want to be able to enable anti-aliasing with wgpu?

**Comment by greatest-ape** [comment]
The features are named like that to avoid conflicts with crate names and for consistency. 

I don't know for sure if log crate is needed.

If you want to add antialiasing flag support with wgpu, that would be great.

**Comment by robbert-vdh** [comment]
They're not consistent this way though. The normal way to name compile-time features in Rust is without the `with-` prefix, that's also how the features in the crate this is mirroring are named. If you do have a feature and a crate dependency with the same name then you can use the `dep:<crate_name>` syntax for the feature, but in this case there are no conflicts like that.

And for the anti aliasing, wouldn't it be better to just have the `Application` set the anti aliasing flag in their render settings and then have the glow integration check if that value is valid instead of adding another constructor flag and doing it the other way around? Now the flag can be specified by the application only to be overridden by `iced_baseview`.

**Comment by greatest-ape** [comment]
I think that the naming conflict I came across was between the glow crate and glow feature. If there is indeed a way to use the same names for features and dependencies without any issues, we can drop the "with" prefix like you're suggesting. I looked for documentation on it and couldn't find it. I still want wgpu prefix for iced_wgpu-related features though.

Possibly. I seem to remember that the cleanest solution would involve having the functionality in raw-gl-context (or now baseview).

**Comment by robbert-vdh** [comment]
Yeah you can use that `dep:` prefix to differentiate between crates and features for feature dependencies! Not sure how I found out about it, either Cargo suggested it (I think that's what happened) or I had to Google it when something similar happened in one of my own crates. I agree with having the `wgpu_` prefix makes it a bit more obvious that those features are specific to the wgpu backend. I went one step further in my own iced bindings and prefixed all OpenGL features with `opengl_` instead of `glow_` as well since the fact that it uses glow is kind of irrelevant, but iced_baseview obviously have to do that.

Oh and that options is actually already part of baseview/raw-gl-context! Right now setting `iced_glow::Settings::antialiasing` actually doesn't do anything with baseview since that option is supposed to be passed to the OpenGL context creation using the `*_SAMPLE_BUFFERS` and `*_SAMPLES` framebuffer arguments, and those are currently determined by `baseview::gl::GlConfig::samples`. So the correct approach would be to modify that value before creating the window if `iced_glow::Settings::antialiasing` contains a value. Then you can still specify it manually in the `WindowOpenOptions`, but you would also have a consistent interface for wgpu and OpenGL versions of the same application.

**Comment by robbert-vdh** [comment]
This would make the interface consistent for the wgpu and glow backends: https://github.com/robbert-vdh/iced_baseview/commit/6021b79b4f96b0f3e52f5898f24518af70799632

**Comment by greatest-ape** [comment]
Ok! It would be easier for me to understand your changes if you open a new PR / change merge target of this one.

**Pull request closed without merging**
